"""Plot continuous density, folded rectangle supports, and component masses."""
import argparse
import json
from pathlib import Path
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.colors import PowerNorm
from matplotlib.patches import Rectangle
from geometry import Geometry
from certify import density_digest


def density_grid(data, epsilon=1/20000):
    L=data['L']; weights=np.asarray(data['weights']); keep=weights>0
    model=Geometry(L,data['B'],np.asarray(data['rectangles'])[keep])
    # Include ALL trapezoid knots. The midpoint value on each cell is its exact
    # average for this piecewise bilinear density (up to floating-point error).
    ends=model.full[:,[0,2]].ravel()
    edges=np.unique(np.r_[np.linspace(0,L,161),ends-epsilon,ends+epsilon])
    edges=edges[(edges>=0)&(edges<=L)]
    mid=(edges[:-1]+edges[1:])/2
    density=np.zeros((len(mid),len(mid)))
    for r,mass in zip(model.full,np.repeat(weights[keep]/8,8)):
        a,b,c,d=r
        tx=np.maximum(0,np.minimum(c,mid+epsilon)-np.maximum(a,mid-epsilon))/(2*epsilon*(c-a))
        ty=np.maximum(0,np.minimum(d,mid+epsilon)-np.maximum(b,mid-epsilon))/(2*epsilon*(d-b))
        density += mass*ty[:,None]*tx[None,:]
    return edges,density


def plot_solution(source,out):
    data=json.loads(Path(source).read_text())
    L=data['L']; weights=np.asarray(data['weights']); ids=np.flatnonzero(weights>0)
    verified=data.get('globally_verified',False)
    if verified:
        if data.get('certificate',{}).get('density_sha256')!=density_digest(data):
            raise ValueError('Verified label rejected: density differs from certificate')
    edges,density=density_grid(data)
    mass_integral=float(np.diff(edges)@density@np.diff(edges))
    if not np.isclose(mass_integral,weights.sum(),rtol=1e-8,atol=1e-8):
        raise ValueError('Plot density mass check failed')
    fig,axes=plt.subplots(1,3,figsize=(16,5.5),layout='constrained',
                          gridspec_kw={'width_ratios':[1,1,1.05]})
    norm=PowerNorm(.35,vmin=0,vmax=float(density.max()))
    mesh=axes[0].pcolormesh(edges,edges,density,cmap='magma',norm=norm,rasterized=True)
    axes[0].set(xlim=(0,L),ylim=(0,L),aspect='equal',title='Continuous density (D4 symmetry)',xlabel='x',ylabel='y')
    fig.colorbar(mesh,ax=axes[0],label='Density (nonlinear color scale)',shrink=.78)
    axes[1].pcolormesh(edges,edges,density,cmap='magma',norm=norm,rasterized=True)
    rects=np.asarray(data['rectangles'])
    for number,i in enumerate(ids,1):
        a,b,c,d=rects[i]
        # Supports generated by this engine lie in the folded quadrant.
        axes[1].add_patch(Rectangle((a,b),c-a,d-b,fill=False,lw=.65,edgecolor='#46def5'))
    axes[1].set(xlim=(0,L/2),ylim=(0,L/2),aspect='equal',title=f'Folded view: {len(ids)} active rectangles',
                xlabel='Distance from left wall',ylabel='Distance from bottom wall')
    order=ids[np.argsort(weights[ids])[::-1]]
    axes[2].barh(np.arange(len(order)),weights[order],color='#416aa3')
    axes[2].set_yticks(np.arange(len(order)),[str(i+1) for i in order],fontsize=7)
    axes[2].invert_yaxis();axes[2].set(title='Mass by rectangle orbit',xlabel='Mass (all 8 copies combined)',ylabel='Candidate index')
    status='VERIFIED: every unit square >= 1.0001' if verified else 'NUMERICAL CANDIDATE: not globally verified'
    fig.suptitle(f'L = {L:g}   |   Total mass = {weights.sum():.9f}   |   {status}',fontsize=13)
    out=Path(out);out.parent.mkdir(parents=True,exist_ok=True)
    fig.savefig(out,dpi=180);plt.close(fig)
    out.with_suffix('.json').write_text(json.dumps({'source':str(source),'density_sha256':density_digest(data),
        'plotted_mass':mass_integral,'mass':float(weights.sum()),'active_rectangles':len(ids),
        'epsilon':1/20000,'globally_verified':verified},indent=2))


if __name__=='__main__':
    ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('candidate',type=Path)
    ap.add_argument('--out',type=Path,required=True)
    args=ap.parse_args();plot_solution(args.candidate,args.out)
